Outgrown/outgrown_be

db/migrate/20230324200357_create_users.rb
db/migrate/20230324200619_create_articles.rb
db/schema.rb
pull_request_template.md

This will add database set up, gems, and PR template

Add initial migrations for database

---

JSON_Schemas.md
app/graphql/mutations/create_article.rb
app/graphql/mutations/create_user.rb
app/graphql/types/article_type.rb
app/graphql/types/mutation_type.rb
app/graphql/types/query_type.rb
app/graphql/types/user_type.rb
app/models/article.rb
db/migrate/20230324200619_create_articles.rb
db/schema.rb

…ation
- [x ] Adds a new feature
feat: adds user create, article create and find for graphql implement…

Feat/adds user create, article create and find for graphql

---

app/graphql/types/query_type.rb
db/seeds.rb
spec/factories/articles.rb

Still in the process of doing so
Added the field all_articles and the method all_articles to the query_type.rb in graphql
Still working on how to do multiple filtering options in the cleanest way.

Feat all articles

---

Gemfile
Gemfile.lock
spec/models/article_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

- [x ] Fixes a bug
Checked testing locally-not working
Updated by shuffling code around until it passed-rewriting code without copy/pasting

fix: testing errors

---

app/graphql/mutations/update_article.rb
app/graphql/types/mutation_type.rb
app/graphql/types/query_type.rb

[Briefly, but clearly describe what you did, and explain any new code.](feat: adds functionality to change user associated with article)

Feat/Update Article User

---

app/graphql/types/query_type.rb
app/graphql/types/user_type.rb

finds user and all associated articles

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/types/article_spec.rb
spec/types/user_spec.rb

Adds testing functionality for GraphQL requests and objects

test: adds basic tests for the GraphQL user type and article type

---

Gemfile.lock

Add a platform to the gem lock

Add bundle lock platform for heroku

---

app/graphql/types/query_type.rb

Adds "null" capabilities to find_articles

Add "null" capabilities to find articles

---

Gemfile
Gemfile.lock
config/initializers/cors.rb

[Briefly, but clearly describe what you did, and explain any new code.](feat:adds rails cors rack settings)

Feat/Cors Rack Allow

---

app/models/article.rb

Change enums to match front end expectations

change enums to match front end expectations

---

db/seeds.rb

Adds seeds to database that make a lot more sense

Adds unique articles and random articles to seeds

---

app/graphql/types/query_type.rb
spec/factories/articles.rb
spec/requests/articles/find_article_spec.rb
spec/types/article_spec.rb

adds test data to type-article, and adds test for find_article query

adds test data to type-article, and adds test for find_article query

---

app/graphql/mutations/update_article.rb
app/graphql/types/query_type.rb
spec/requests/articles/all_users_spec.rb

[Briefly, but clearly describe what you did, and explain any new code.](feat: adds all users request functionality)

feat: adds all users request functionality

---

app/graphql/types/query_type.rb

[Briefly, but clearly describe what you did, and explain any new code.](expand: add limit to all articles)

expand: add limit to all articles

---

app/models/article.rb
spec/requests/articles/all_articles_spec.rb

- [x ] Cleans up (logs, tests, etc.)
Added happy path tests for all articles query

Add happy path test to all_articles query

---

app/models/article.rb
spec/requests/articles/all_articles_spec.rb
spec/requests/articles/create_article_spec.rb

- [ x] Cleans up (logs, tests, etc.)
Adds happy path test for create_article mutation

Testing create article

---

spec/requests/articles/create_user_spec.rb
spec/requests/articles/find_user_spec.rb

- [ x] Cleans up (logs, tests, etc.)
rspec
happy path test for find and create user
added rspec testing for our graphql user queries 

add tests for find and create user

---

spec/requests/articles/create_article_spec.rb

Added simple sad path testing for create article mutation

Add sad path test for create article

---

db/seeds.rb

Fix images in seeds

---

app/graphql/mutations/create_user.rb
spec/requests/users/create_user_spec.rb
spec/requests/users/find_user_spec.rb

added sad paths to create user and find user
